package boundary;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import entity.SessioneDiAllenamento;
import controller.Control_session;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.util.Locale;

public class FormSessioniDiAllenamento {

    private Long id_utente_autenticato;

    private JPanel PanelBase;
    private JPanel PanelCentrale;
    private JScrollPane Scorrimento;
    private JPanel Header;
    private JPanel Footer;

    private void aggiungiComponenti() {
        Control_session c_session = Control_session.getInstance();
        PanelCentrale.setLayout(new BoxLayout(PanelCentrale, BoxLayout.Y_AXIS));
        for (SessioneDiAllenamento s : c_session.getSessioneforUtente(c_session.getAutenticato())) {
            Long id_sessione = s.getId();
            SchedaSingola scheda = new SchedaSingola(id_sessione, this);
            PanelCentrale.add(scheda.$$$getRootComponent$$$());
            PanelCentrale.add(Box.createVerticalStrut(5));
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        PanelBase = new JPanel();
        PanelBase.setLayout(new GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        PanelBase.setBackground(new Color(-1));
        PanelBase.setMaximumSize(new Dimension(2147483647, 500));
        PanelBase.setMinimumSize(new Dimension(28, 500));
        PanelBase.setPreferredSize(new Dimension(750, 500));
        Scorrimento = new JScrollPane();
        Scorrimento.setHorizontalScrollBarPolicy(30);
        Scorrimento.setInheritsPopupMenu(true);
        Scorrimento.setVerticalScrollBarPolicy(22);
        PanelBase.add(Scorrimento, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        PanelCentrale = new JPanel();
        PanelCentrale.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        PanelCentrale.setBackground(new Color(-657936));
        Font PanelCentraleFont = this.$$$getFont$$$("Segoe UI Semibold", Font.BOLD, 0, PanelCentrale.getFont());
        if (PanelCentraleFont != null) PanelCentrale.setFont(PanelCentraleFont);
        PanelCentrale.setMaximumSize(new Dimension(-1, -1));
        PanelCentrale.setMinimumSize(new Dimension(-1, -1));
        PanelCentrale.setOpaque(true);
        PanelCentrale.setPreferredSize(new Dimension(-1, -1));
        Scorrimento.setViewportView(PanelCentrale);
        Header = new JPanel();
        Header.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        PanelBase.add(Header, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(-1, 50), new Dimension(-1, 50), new Dimension(-1, 50), 0, false));
        final JLabel label1 = new JLabel();
        Font label1Font = this.$$$getFont$$$("Segoe UI Semibold", Font.BOLD, 28, label1.getFont());
        if (label1Font != null) label1.setFont(label1Font);
        label1.setHorizontalAlignment(0);
        label1.setHorizontalTextPosition(0);
        label1.setOpaque(false);
        label1.setPreferredSize(new Dimension(100, 100));
        label1.setText("I TUOI ALLENAMENTI");
        Header.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(-1, 50), new Dimension(-1, 50), new Dimension(-1, 50), 0, false));
        final Spacer spacer1 = new Spacer();
        Header.add(spacer1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        Footer = new JPanel();
        Footer.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        PanelBase.add(Footer, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        label1.setLabelFor(Scorrimento);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return PanelBase;
    }

    public static void main(String[] args) {

        FormSessioniDiAllenamento form_base = new FormSessioniDiAllenamento();
        form_base.setup();

    }

    public void refresh() {
        // Svuota il pannello centrale
        PanelCentrale.removeAll();
        // Ricostruisci le schede
        aggiungiComponenti();
        // Forza il ricalcolo del layout
        PanelCentrale.revalidate();
        PanelCentrale.repaint();
    }

    public void setup() {
        JFrame frame = new JFrame();
        frame.setTitle("Visualizza allenamenti");
        this.Scorrimento.getVerticalScrollBar().setUnitIncrement(20);
        frame.setContentPane(this.PanelBase);
        this.aggiungiComponenti();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setResizable(false);

        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }
}
