package boundary;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import entity.SessioneDiAllenamento;
import controller.Control_session;

import javax.swing.*;
import java.awt.*;

public class FormSessioniDiAllenamento {

    private Long id_utente_autenticato;

    private JPanel PanelBase;
    private JPanel PanelCentrale;
    private JScrollPane Scorrimento;
    private JPanel Header;
    private JPanel Footer;


    private void aggiungiComponenti() {
        Control_session c_session = new Control_session();
        for (SessioneDiAllenamento s : c_session.stubGetSessioneforUtente(id_utente_autenticato)) {
            SchedaSingola scheda = new SchedaSingola();
            PanelCentrale.setLayout(new GridLayout(0, 1, 0, 8));
            PanelCentrale.add(scheda.$$$getRootComponent$$$());
        }
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        PanelBase = new JPanel();
        PanelBase.setLayout(new GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        PanelBase.setBackground(new Color(-1));
        PanelBase.setMaximumSize(new Dimension(2147483647, 500));
        PanelBase.setMinimumSize(new Dimension(28, 500));
        PanelBase.setPreferredSize(new Dimension(750, 500));
        Scorrimento = new JScrollPane();
        Scorrimento.setHorizontalScrollBarPolicy(30);
        Scorrimento.setInheritsPopupMenu(true);
        Scorrimento.setVerticalScrollBarPolicy(22);
        PanelBase.add(Scorrimento, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        PanelCentrale = new JPanel();
        PanelCentrale.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        PanelCentrale.setBackground(new Color(-1));
        PanelCentrale.setMaximumSize(new Dimension(32767, 1200));
        PanelCentrale.setMinimumSize(new Dimension(10, 1200));
        PanelCentrale.setOpaque(true);
        PanelCentrale.setPreferredSize(new Dimension(10, 1200));
        Scorrimento.setViewportView(PanelCentrale);
        final JLabel label1 = new JLabel();
        label1.setHorizontalAlignment(0);
        label1.setHorizontalTextPosition(0);
        label1.setOpaque(false);
        label1.setPreferredSize(new Dimension(100, 100));
        label1.setText("I TUOI ALLENAMENTI");
        PanelCentrale.add(label1);
        Header = new JPanel();
        Header.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        PanelBase.add(Header, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        Footer = new JPanel();
        Footer.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        PanelBase.add(Footer, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        label1.setLabelFor(Scorrimento);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return PanelBase;
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame();
        frame.setTitle("Visualizza allenamenti");
        FormSessioniDiAllenamento form_base = new FormSessioniDiAllenamento();
        form_base.Scorrimento.getVerticalScrollBar().setUnitIncrement(20);
        frame.setContentPane(form_base.PanelBase);
        form_base.aggiungiComponenti();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setResizable(false);

        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }

}
