package boundary;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import controller.Controller;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.DateTimeException;
import java.time.LocalDate;
import java.util.Locale;
import java.util.Map;
import java.util.Set;

public class FormListaSessioni {

    private JPanel PanelBase;
    private JPanel PanelCentrale;
    private JScrollPane Scorrimento;
    private JPanel Header;
    private JPanel Footer;
    private JLabel emptyLbl;
    private JCheckBox ASSEGNATECheckBox;
    private JCheckBox INCORSOCheckBox;
    private JCheckBox COMPLETATECheckBox;
    private JLabel PRECEDENTE_A;
    private JTextField GIORNO;
    private JTextField MESE;
    private JTextField ANNO;
    private JButton APPLICA;


    private void aggiungiComponenti() {
        Controller c_session = Controller.getInstance();
        PanelCentrale.setLayout(new BoxLayout(PanelCentrale, BoxLayout.Y_AXIS));
        Set<Long> sessioni = c_session.getIdSessioniPerUtente(c_session.getIdUtenteAutenticato());

        LocalDate data_filtro;
        try {
            data_filtro = inizializzaData();
        } catch (RuntimeException r) {
            data_filtro = LocalDate.of(4000, 12, 31);
        }

        if (data_filtro != null) {
            for (Long s : sessioni) {
                Map<String, Object> dettaglio = c_session.getDettaglioSessionePerId(s);
                impaginaSessione(s, dettaglio, data_filtro);
            }
        }
        PanelCentrale.setPreferredSize(null);
    }

    private void impaginaSessione(Long s, Map<String, Object> dettaglio, LocalDate data_filtro) {
        if (((LocalDate) dettaglio.get("data")).isBefore(data_filtro)) {
            switch ((String) dettaglio.get("stato")) {
                case "ASSEGNATA":
                    if (ASSEGNATECheckBox.getModel().isSelected()) {
                        SchedaSingolaSessione scheda = new SchedaSingolaSessione(s, this);
                        PanelCentrale.add(scheda.$$$getRootComponent$$$());
                        PanelCentrale.add(Box.createVerticalStrut(5));
                        emptyLbl.setVisible(false);
                    }
                    break;

                case "IN_CORSO":
                    if (INCORSOCheckBox.getModel().isSelected()) {
                        SchedaSingolaSessione scheda = new SchedaSingolaSessione(s, this);
                        PanelCentrale.add(scheda.$$$getRootComponent$$$());
                        PanelCentrale.add(Box.createVerticalStrut(5));
                        emptyLbl.setVisible(false);
                    }
                    break;

                case "COMPLETATA":
                    if (COMPLETATECheckBox.getModel().isSelected()) {
                        SchedaSingolaSessione scheda = new SchedaSingolaSessione(s, this);
                        PanelCentrale.add(scheda.$$$getRootComponent$$$());
                        PanelCentrale.add(Box.createVerticalStrut(5));
                        emptyLbl.setVisible(false);
                    }
                    break;

            }
        }

    }

    private LocalDate inizializzaData() {
        LocalDate data_filtro = null;
        try {
            String anno;
            String mese;
            String giorno;

            if (ANNO.getText().isEmpty()) {
                anno = "4000";
            } else {
                anno = ANNO.getText();
            }

            if (MESE.getText().isEmpty()) {
                mese = "12";
            } else {
                mese = MESE.getText();
            }

            if (GIORNO.getText().isEmpty()) {
                giorno = "31";
            } else {
                giorno = GIORNO.getText();
            }

            data_filtro = LocalDate.of(Integer.parseInt(anno), Integer.parseInt(mese), Integer.parseInt(giorno));

        } catch (DateTimeException e) {
            JOptionPane.showMessageDialog(null, "La data inserita non è una data realmente esistente", "Errore inserimento data", JOptionPane.ERROR_MESSAGE);
            throw e;
        } catch (NumberFormatException n) {
            JOptionPane.showMessageDialog(null, "Inserire nel filtro data solo numeri interi", "Errore inserimento data", JOptionPane.ERROR_MESSAGE);
            throw n;
        }
        return data_filtro;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        PanelBase = new JPanel();
        PanelBase.setLayout(new GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        PanelBase.setBackground(new Color(-1));
        PanelBase.setMaximumSize(new Dimension(750, 600));
        PanelBase.setMinimumSize(new Dimension(28, 500));
        PanelBase.setPreferredSize(new Dimension(750, 600));
        Scorrimento = new JScrollPane();
        Scorrimento.setHorizontalScrollBarPolicy(30);
        Scorrimento.setInheritsPopupMenu(true);
        Scorrimento.setVerticalScrollBarPolicy(22);
        PanelBase.add(Scorrimento, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        PanelCentrale = new JPanel();
        PanelCentrale.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        PanelCentrale.setBackground(new Color(-657936));
        Font PanelCentraleFont = this.$$$getFont$$$("Segoe UI Semibold", Font.BOLD, 0, PanelCentrale.getFont());
        if (PanelCentraleFont != null) PanelCentrale.setFont(PanelCentraleFont);
        PanelCentrale.setMaximumSize(new Dimension(-1, -1));
        PanelCentrale.setMinimumSize(new Dimension(-1, -1));
        PanelCentrale.setOpaque(true);
        PanelCentrale.setPreferredSize(new Dimension(-1, 180));
        Scorrimento.setViewportView(PanelCentrale);
        Header = new JPanel();
        Header.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        PanelBase.add(Header, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(-1, 50), new Dimension(-1, 50), new Dimension(-1, 50), 0, false));
        final JLabel label1 = new JLabel();
        Font label1Font = this.$$$getFont$$$("Segoe UI Semibold", Font.BOLD, 28, label1.getFont());
        if (label1Font != null) label1.setFont(label1Font);
        label1.setHorizontalAlignment(0);
        label1.setHorizontalTextPosition(0);
        label1.setOpaque(false);
        label1.setPreferredSize(new Dimension(100, 100));
        label1.setText("I TUOI ALLENAMENTI");
        Header.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(-1, 50), new Dimension(-1, 50), new Dimension(-1, 50), 0, false));
        final Spacer spacer1 = new Spacer();
        Header.add(spacer1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        Footer = new JPanel();
        Footer.setLayout(new GridLayoutManager(4, 18, new Insets(0, 0, 0, 0), -1, -1));
        PanelBase.add(Footer, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, new Dimension(-1, 180), 1, false));
        emptyLbl = new JLabel();
        Font emptyLblFont = this.$$$getFont$$$(null, -1, 16, emptyLbl.getFont());
        if (emptyLblFont != null) emptyLbl.setFont(emptyLblFont);
        emptyLbl.setText("Nessuna sessione trovata");
        Footer.add(emptyLbl, new GridConstraints(3, 0, 1, 18, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        ASSEGNATECheckBox = new JCheckBox();
        ASSEGNATECheckBox.setText("ASSEGNATE");
        Footer.add(ASSEGNATECheckBox, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        INCORSOCheckBox = new JCheckBox();
        INCORSOCheckBox.setText("IN CORSO");
        Footer.add(INCORSOCheckBox, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        COMPLETATECheckBox = new JCheckBox();
        COMPLETATECheckBox.setText("COMPLETATE");
        Footer.add(COMPLETATECheckBox, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        Footer.add(spacer2, new GridConstraints(1, 2, 1, 9, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        PRECEDENTE_A = new JLabel();
        PRECEDENTE_A.setText("PRECEDENTE A:");
        Footer.add(PRECEDENTE_A, new GridConstraints(0, 11, 1, 5, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer3 = new Spacer();
        Footer.add(spacer3, new GridConstraints(0, 2, 1, 9, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final Spacer spacer4 = new Spacer();
        Footer.add(spacer4, new GridConstraints(2, 2, 1, 9, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        ANNO = new JTextField();
        ANNO.setText("");
        Footer.add(ANNO, new GridConstraints(1, 15, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(50, -1), new Dimension(50, -1), 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("/");
        Footer.add(label2, new GridConstraints(1, 14, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        MESE = new JTextField();
        Footer.add(MESE, new GridConstraints(1, 13, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(50, -1), new Dimension(50, -1), 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("/");
        Footer.add(label3, new GridConstraints(1, 12, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        GIORNO = new JTextField();
        GIORNO.setHorizontalAlignment(4);
        Footer.add(GIORNO, new GridConstraints(1, 11, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(50, -1), new Dimension(50, -1), 0, false));
        APPLICA = new JButton();
        APPLICA.setText("APPLICA FILTRI");
        Footer.add(APPLICA, new GridConstraints(1, 16, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer5 = new Spacer();
        Footer.add(spacer5, new GridConstraints(1, 17, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final Spacer spacer6 = new Spacer();
        Footer.add(spacer6, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        label1.setLabelFor(Scorrimento);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return PanelBase;
    }

    public void refreshPanelCentrale() {
        // Svuota il pannello centrale
        PanelCentrale.removeAll();
        // Ricostruisci le schede
        aggiungiComponenti();
        // Forza il ricalcolo del layout
        PanelCentrale.revalidate();
        PanelCentrale.repaint();
        Scorrimento.getViewport().revalidate();
    }

    public void setup() {
        JFrame frame = new JFrame();
        frame.setTitle("Visualizza allenamenti");
        this.Scorrimento.getVerticalScrollBar().setUnitIncrement(20);
        ASSEGNATECheckBox.setSelected(true);
        INCORSOCheckBox.setSelected(true);
        COMPLETATECheckBox.setSelected(true);
        APPLICA.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                refreshPanelCentrale();
            }
        });
        frame.setContentPane(this.PanelBase);
        this.aggiungiComponenti();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setResizable(false);

        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }

    public static void main(String[] args) {
        FormListaSessioni form_base = new FormListaSessioni();
        form_base.setup();
    }
}
