package boundary;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import entity.Esercizio;
import entity.SessioneDiAllenamento;

import javax.swing.*;
import java.awt.*;

public class SchedaSingolaEsercizio {
    private JPanel PanelBase;
    private JTextField textFieldNota;
    private JTextField textFieldRisultato;
    private JLabel lblDescrizione;
    private JLabel lblRisultatoAtteso;
    private JLabel lblTitolo;
    private Long id;

    public SchedaSingolaEsercizio(Esercizio esercizio) {
        this.id = esercizio.getId();
        this.lblDescrizione.setText(esercizio.getDescrizione());
        this.lblTitolo.setText(esercizio.getNome());

        if (esercizio.getSessione().getStato() == SessioneDiAllenamento.Stato.COMPLETATA) {
            // Mostra i valori registrati e disabilita la modifica
            textFieldNota.setText(esercizio.getRisultato() != null ? esercizio.getRisultato().getNota() : "");
            textFieldRisultato.setText(esercizio.getRisultato().getRisultato() != null ? esercizio.getRisultato().getRisultato().toString() : "");
            textFieldNota.setEditable(false);
            textFieldRisultato.setEditable(false);
            // Opzionale: cambia colore di sfondo
            textFieldNota.setBackground(Color.LIGHT_GRAY);
            textFieldRisultato.setBackground(Color.LIGHT_GRAY);
        } else {
            // Campi vuoti e modificabili
            textFieldNota.setText("");
            textFieldRisultato.setText("");
            textFieldNota.setEditable(true);
            textFieldRisultato.setEditable(true);
        }


    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        PanelBase = new JPanel();
        PanelBase.setLayout(new GridLayoutManager(5, 2, new Insets(10, 10, 10, 10), -1, -1));
        PanelBase.setPreferredSize(new Dimension(720, 155));
        final JLabel label1 = new JLabel();
        label1.setText("TITOLO");
        PanelBase.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("DESCRIZIONE");
        PanelBase.add(label2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("RISULTATO ATTESO");
        PanelBase.add(label3, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblDescrizione = new JLabel();
        lblDescrizione.setText("DESCRIZIONE EFFETTIVA");
        PanelBase.add(lblDescrizione, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblRisultatoAtteso = new JLabel();
        lblRisultatoAtteso.setText("");
        PanelBase.add(lblRisultatoAtteso, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label4 = new JLabel();
        label4.setText("REGISTRA NOTA");
        PanelBase.add(label4, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label5 = new JLabel();
        label5.setText("REGISTRA RISULTATO");
        PanelBase.add(label5, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        textFieldNota = new JTextField();
        textFieldNota.setText("nota");
        PanelBase.add(textFieldNota, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        textFieldRisultato = new JTextField();
        textFieldRisultato.setText("risultato");
        PanelBase.add(textFieldRisultato, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        lblTitolo = new JLabel();
        lblTitolo.setText("TITOLO EFFETTIVO");
        PanelBase.add(lblTitolo, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return PanelBase;
    }

    public String getValueNota() {
        return textFieldNota.getText();
    }

    public String getValueRisultato() {
        return textFieldRisultato.getText();
    }

    public Long getId() {
        return id;
    }
}
