package boundary;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import controller.Control_session;

import javax.swing.*;
import java.awt.*;
import java.time.Duration;
import java.util.Map;

public class SchedaSingolaEsercizio {
    private JPanel PanelBase;
    private JTextField textFieldNota;
    private JTextField textFieldRisultato;
    private JLabel lblDescrizione;
    private JLabel lblRisultatoAtteso;
    private JLabel lblTitolo;
    private Long id;


    /**
     * Costruttore SchedaSingolaEsercizio
     * @param id_esercizio Id Esercizio
     * @param id_sessione  Id SessioneDiAllenamento
     * */
    public SchedaSingolaEsercizio(Long id_sessione, Long id_esercizio) {

        this.id = id_esercizio;

        Control_session controller = Control_session.getInstance();

        Map<String,Object> dettaglio = controller.getDettaglioEsercizioPerId(id_sessione, id_esercizio);


        this.lblDescrizione.setText((String)dettaglio.get("descrizione"));
        this.lblTitolo.setText((String)dettaglio.get("nome"));

        textFieldNota.setText(dettaglio.get("nota") != null ? (String) dettaglio.get("nota") : "");
        if(dettaglio.get("risultato") != null) {
            if (dettaglio.get("risultato") instanceof Integer)
                textFieldRisultato.setText(dettaglio.get("risultato").toString());
            else
                textFieldRisultato.setText(Long.valueOf(((Duration) dettaglio.get("risultato")).toMinutes()).toString());
        }else
            textFieldRisultato.setText("");

        if (((String) dettaglio.get("stato")).equalsIgnoreCase("completata")) {
            // Mostra i valori registrati e disabilita la modifica
            textFieldNota.setEditable(false);
            textFieldRisultato.setEditable(false);
            // Opzionale: cambia colore di sfondo
            textFieldNota.setBackground(Color.LIGHT_GRAY);
            textFieldRisultato.setBackground(Color.LIGHT_GRAY);
        } else {
            // Campi vuoti e modificabili
            textFieldNota.setEditable(true);
            textFieldRisultato.setEditable(true);
        }


    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        PanelBase = new JPanel();
        PanelBase.setLayout(new GridLayoutManager(5, 2, new Insets(10, 10, 10, 10), -1, -1));
        PanelBase.setMaximumSize(new Dimension(2147483647, 130));
        PanelBase.setMinimumSize(new Dimension(342, 130));
        PanelBase.setPreferredSize(new Dimension(720, 130));
        final JLabel label1 = new JLabel();
        label1.setText("TITOLO");
        PanelBase.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("DESCRIZIONE");
        PanelBase.add(label2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("RISULTATO ATTESO");
        PanelBase.add(label3, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblDescrizione = new JLabel();
        lblDescrizione.setText("DESCRIZIONE EFFETTIVA");
        PanelBase.add(lblDescrizione, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblRisultatoAtteso = new JLabel();
        lblRisultatoAtteso.setText("");
        PanelBase.add(lblRisultatoAtteso, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label4 = new JLabel();
        label4.setText("REGISTRA NOTA");
        PanelBase.add(label4, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label5 = new JLabel();
        label5.setText("REGISTRA RISULTATO");
        PanelBase.add(label5, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        textFieldNota = new JTextField();
        textFieldNota.setText("nota");
        PanelBase.add(textFieldNota, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        textFieldRisultato = new JTextField();
        textFieldRisultato.setText("risultato");
        PanelBase.add(textFieldRisultato, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        lblTitolo = new JLabel();
        lblTitolo.setText("TITOLO EFFETTIVO");
        PanelBase.add(lblTitolo, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return PanelBase;
    }

    /**
     * Getter Nota
     * @return Testo della Nota come String
     * */
    public String getTestoNota() {
        return textFieldNota.getText();
    }

    /**
     * Getter Risultato
     * @return  Testo del Risultato come String
     * */
    public String getTestoRisultato() {
        return textFieldRisultato.getText();
    }

    /**
     * Getter Id Esercizio
     * @return Id Esercizio
     * */
    public Long getIdEsercizio() {
        return id;
    }
}
