package boundary;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import controller.Control_session;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Locale;
import java.util.Map;

public class SchedaSingola extends JFrame {

    private JButton VISUALIZZADETTAGLIOButton;
    private JPanel PanelBase;
    private JLabel Titolo;
    private JLabel Descrizione_placeholder;
    private JLabel Descrizione_real;
    private JLabel Allenatore_placeholder;
    private JLabel Allenatore_real;
    private JLabel Stato_placeholder;
    private JLabel Data_placeholder;
    private JLabel Stato_real;
    private JLabel Data_real;

    private FormSessioniDiAllenamento parentForm;


    public SchedaSingola(Long id_sessione, FormSessioniDiAllenamento parentForm) {

        this.parentForm = parentForm;
        Control_session controller = Control_session.getInstance();

        Map<String, Object> dettaglio = controller.getDettaglioSessionePerId(id_sessione);

        this.Titolo.setText((String) dettaglio.get("titolo"));
        this.Allenatore_real.setText((String) dettaglio.get("allenatore"));
        this.Descrizione_real.setText((String) dettaglio.get("descrizione"));
        this.Stato_real.setText((String) dettaglio.get("stato"));

        switch ((String) dettaglio.get("stato")) {
            case "COMPLETATA":
                this.Stato_real.setForeground(Color.GREEN);
                break;
            case "IN_CORSO":
                this.Stato_real.setForeground(Color.ORANGE);
                break;
            case "ASSEGNATA":
                this.Stato_real.setForeground(Color.BLUE);
                break;
            default:
                this.Stato_real.setForeground(Color.BLACK);
        }


        this.Data_real.setText(dettaglio.get("data").toString());

        VISUALIZZADETTAGLIOButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dettaglioEsercizi(id_sessione);
            }

        });
    }

    private void dettaglioEsercizi(Long id_sessione) {

        JFrame parentFrame = (JFrame) SwingUtilities.getWindowAncestor(PanelBase);

        FormEsercizi formEsercizi = new FormEsercizi(id_sessione, parentFrame, parentForm);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        PanelBase = new JPanel();
        PanelBase.setLayout(new GridLayoutManager(4, 6, new Insets(10, 10, 10, 10), -1, -1));
        PanelBase.setBackground(new Color(-657936));
        PanelBase.setForeground(new Color(-13884898));
        PanelBase.setMaximumSize(new Dimension(1000, 100));
        PanelBase.setMinimumSize(new Dimension(1000, 100));
        PanelBase.setPreferredSize(new Dimension(720, 100));
        Titolo = new JLabel();
        Titolo.setText("Titolo");
        PanelBase.add(Titolo, new GridConstraints(0, 0, 1, 6, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        Descrizione_placeholder = new JLabel();
        Descrizione_placeholder.setText("Descrizione:");
        PanelBase.add(Descrizione_placeholder, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        Allenatore_placeholder = new JLabel();
        Allenatore_placeholder.setText("Allenatore:");
        PanelBase.add(Allenatore_placeholder, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        Descrizione_real = new JLabel();
        Descrizione_real.setText("NUMERO ESERCIZI EFFETTIVO");
        PanelBase.add(Descrizione_real, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        Allenatore_real = new JLabel();
        Allenatore_real.setBackground(new Color(-460294));
        Font Allenatore_realFont = this.$$$getFont$$$("Segoe UI Semibold", Font.PLAIN, -1, Allenatore_real.getFont());
        if (Allenatore_realFont != null) Allenatore_real.setFont(Allenatore_realFont);
        Allenatore_real.setForeground(new Color(-14605015));
        Allenatore_real.setText("ALLENATORE EFFETTIVO");
        PanelBase.add(Allenatore_real, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        Stato_placeholder = new JLabel();
        Stato_placeholder.setText("Stato:");
        PanelBase.add(Stato_placeholder, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        Data_placeholder = new JLabel();
        Data_placeholder.setText("Data:");
        PanelBase.add(Data_placeholder, new GridConstraints(2, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        Stato_real = new JLabel();
        Stato_real.setText("STATO EFFETTIVO");
        PanelBase.add(Stato_real, new GridConstraints(1, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        Data_real = new JLabel();
        Data_real.setText("DATA EFFETTIVA");
        PanelBase.add(Data_real, new GridConstraints(2, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        VISUALIZZADETTAGLIOButton = new JButton();
        VISUALIZZADETTAGLIOButton.setText("VISUALIZZA");
        PanelBase.add(VISUALIZZADETTAGLIOButton, new GridConstraints(1, 5, 2, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        PanelBase.add(spacer1, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        PanelBase.add(spacer2, new GridConstraints(1, 4, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return PanelBase;
    }

}
