package boundary;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;

public class SchedaSingola {

    private JButton VISUALIZZADETTAGLIOButton;
    private JButton COMPLETASESSIONEButton;
    private JPanel PanelBase;
    private JLabel Titolo;
    private JLabel Esercizi_placeholder;
    private JLabel Esercizi_real;
    private JLabel Allenatore_placeholder;
    private JLabel Allenatore_real;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        PanelBase = new JPanel();
        PanelBase.setLayout(new GridLayoutManager(6, 5, new Insets(10, 10, 10, 10), -1, -1));
        PanelBase.setBackground(new Color(-2039584));
        PanelBase.setMaximumSize(new Dimension(1000, 150));
        PanelBase.setMinimumSize(new Dimension(1000, 150));
        PanelBase.setPreferredSize(new Dimension(720, 130));
        final Spacer spacer1 = new Spacer();
        PanelBase.add(spacer1, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        COMPLETASESSIONEButton = new JButton();
        COMPLETASESSIONEButton.setText("COMPLETA SESSIONE");
        PanelBase.add(COMPLETASESSIONEButton, new GridConstraints(4, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        Titolo = new JLabel();
        Titolo.setText("TITOLO DELLA SESSIONE");
        PanelBase.add(Titolo, new GridConstraints(0, 0, 1, 5, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        Esercizi_placeholder = new JLabel();
        Esercizi_placeholder.setText("NUMERO DI ESERCIZI:");
        PanelBase.add(Esercizi_placeholder, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        Allenatore_placeholder = new JLabel();
        Allenatore_placeholder.setText("ALLENATORE:");
        PanelBase.add(Allenatore_placeholder, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        Esercizi_real = new JLabel();
        Esercizi_real.setText("NUMERO ESERCIZI EFFETTIVO");
        PanelBase.add(Esercizi_real, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        Allenatore_real = new JLabel();
        Allenatore_real.setText("ALLENATORE EFFETTIVO");
        PanelBase.add(Allenatore_real, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        VISUALIZZADETTAGLIOButton = new JButton();
        VISUALIZZADETTAGLIOButton.setText("VISUALIZZA DETTAGLIO");
        PanelBase.add(VISUALIZZADETTAGLIOButton, new GridConstraints(4, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        PanelBase.add(spacer2, new GridConstraints(5, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final Spacer spacer3 = new Spacer();
        PanelBase.add(spacer3, new GridConstraints(4, 4, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final Spacer spacer4 = new Spacer();
        PanelBase.add(spacer4, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return PanelBase;
    }

}
